import { NativeModules } from 'react-native';
const MediaLibrarayModule = NativeModules.MediaLibraryModule;
export const libraryAuthorized = MediaLibrarayModule.libraryAuthorized;
export const requestLibraryAuthorization = MediaLibrarayModule.requestLibraryAuthorization;
export const cameraAuthorized = MediaLibrarayModule.cameraAuthorized;
export const requestCameraAuthorization = MediaLibrarayModule.requestCameraAuthorization;
export const startCameraPreview = MediaLibrarayModule.startCameraPreview;
export const stopCameraPreview = MediaLibrarayModule.stopCameraPreview;
export const fetchAllAssets = MediaLibrarayModule.fetchAllAssets;
export const fetchAllAlbums = MediaLibrarayModule.fetchAllAlbums;
export const clear = MediaLibrarayModule.clear;
export const finishSelectMedia = MediaLibrarayModule.finishSelectMedia;
export const fetchVideoURL = MediaLibrarayModule.fetchVideoURL;
export const onSelectAlbumAtIndex = MediaLibrarayModule.onSelectAlbumAtIndex;
export const compressVideo = MediaLibrarayModule.compressVideo;
